/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestUploadRouteImport } from './routes/test-upload'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppFamilyIndexRouteImport } from './routes/app/family/index'
import { Route as AppAssetsIndexRouteImport } from './routes/app/assets/index'
import { Route as AppAgreementIndexRouteImport } from './routes/app/agreement/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as ApiUploadIndexRouteImport } from './routes/api/upload/index'
import { Route as AppProfileViewRouteImport } from './routes/app/profile/view'
import { Route as AppProfileEditRouteImport } from './routes/app/profile/edit'
import { Route as AppFamilyViewRouteImport } from './routes/app/family/view'
import { Route as AppFamilyEditRouteImport } from './routes/app/family/edit'
import { Route as AppFamilyAddRouteImport } from './routes/app/family/add'
import { Route as AppAssetsAddRouteImport } from './routes/app/assets/add'
import { Route as AppAgreementCreateRouteImport } from './routes/app/agreement/create'
import { Route as AppAdminDashboardRouteImport } from './routes/app/admin/dashboard'
import { Route as ApiFileKeyRouteImport } from './routes/api/file/$key'
import { Route as ApiFileSplatRouteImport } from './routes/api/file/$'
import { Route as ApiFamilySearchRouteImport } from './routes/api/family/search'
import { Route as ApiFamilySplatRouteImport } from './routes/api/family/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssetSplatRouteImport } from './routes/api/asset/$'
import { Route as ApiAgreementSplatRouteImport } from './routes/api/agreement/$'
import { Route as ApiAgentChatRouteImport } from './routes/api/agent/chat'
import { Route as AppAssetsViewIndexRouteImport } from './routes/app/assets/view/index'
import { Route as AppAssetsEditIndexRouteImport } from './routes/app/assets/edit/index'
import { Route as AppAgreementViewIndexRouteImport } from './routes/app/agreement/view/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/app/admin/users/index'
import { Route as AppAdminAssetsIndexRouteImport } from './routes/app/admin/assets/index'
import { Route as AppAdminAgreementsIndexRouteImport } from './routes/app/admin/agreements/index'
import { Route as ApiUploadJsonIndexRouteImport } from './routes/api/upload/json/index'
import { Route as AppAssetsViewIdRouteImport } from './routes/app/assets/view/$id'
import { Route as AppAssetsEditIdRouteImport } from './routes/app/assets/edit/$id'
import { Route as AppAgreementViewIdRouteImport } from './routes/app/agreement/view/$id'
import { Route as AppAdminUsersIdRouteImport } from './routes/app/admin/users/$id'
import { Route as ApiUserProfileSplatRouteImport } from './routes/api/user/profile/$'
import { Route as ApiUserNotificationPreferencesSplatRouteImport } from './routes/api/user/notification-preferences/$'
import { Route as ApiAgentPendingActionsConfirmRouteImport } from './routes/api/agent/pending-actions/confirm'
import { Route as ApiAgentConversationsSplatRouteImport } from './routes/api/agent/conversations/$'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users/$id'
import { Route as ApiAdminUsersSplatRouteImport } from './routes/api/admin/users/$'
import { Route as ApiAdminSessionSplatRouteImport } from './routes/api/admin/session/$'
import { Route as ApiAdminLogoutSplatRouteImport } from './routes/api/admin/logout/$'
import { Route as ApiAdminLoginSplatRouteImport } from './routes/api/admin/login/$'
import { Route as ApiAdminAssetsSplatRouteImport } from './routes/api/admin/assets/$'
import { Route as ApiAdminAgreementsSplatRouteImport } from './routes/api/admin/agreements/$'
import { Route as AppAdminAgreementsSignByIcIndexRouteImport } from './routes/app/admin/agreements/sign-by-ic/index'
import { Route as AppAdminAgreementsPendingWitnessIndexRouteImport } from './routes/app/admin/agreements/pending-witness/index'
import { Route as ApiAgreementIdStatusSplatRouteImport } from './routes/api/agreement/$id/status/$'
import { Route as ApiAgreementIdBeneficiariesSplatRouteImport } from './routes/api/agreement/$id/beneficiaries/$'
import { Route as ApiAgreementIdAssetsSplatRouteImport } from './routes/api/agreement/$id/assets/$'
import { Route as ApiAgentConversationsIdSplatRouteImport } from './routes/api/agent/conversations/$id/$'
import { Route as ApiAdminAgreementsSignOnBehalfSplatRouteImport } from './routes/api/admin/agreements/sign-on-behalf/$'
import { Route as ApiAdminAgreementsPendingWitnessSplatRouteImport } from './routes/api/admin/agreements/pending-witness/$'
import { Route as ApiAdminAgreementsIdSplatRouteImport } from './routes/api/admin/agreements/$id/$'
import { Route as ApiAgreementIdSignWitnessSplatRouteImport } from './routes/api/agreement/$id/sign/witness/$'
import { Route as ApiAgreementIdSignOwnerSplatRouteImport } from './routes/api/agreement/$id/sign/owner/$'
import { Route as ApiAgreementIdSignBeneficiarySplatRouteImport } from './routes/api/agreement/$id/sign/beneficiary/$'
import { Route as ApiAdminAgreementsByIcIcNumberSplatRouteImport } from './routes/api/admin/agreements/by-ic/$icNumber/$'

const TestUploadRoute = TestUploadRouteImport.update({
  id: '/test-upload',
  path: '/test-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyIndexRoute = AppFamilyIndexRouteImport.update({
  id: '/family/',
  path: '/family/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementIndexRoute = AppAgreementIndexRouteImport.update({
  id: '/agreement/',
  path: '/agreement/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadIndexRoute = ApiUploadIndexRouteImport.update({
  id: '/api/upload/',
  path: '/api/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileViewRoute = AppProfileViewRouteImport.update({
  id: '/profile/view',
  path: '/profile/view',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyViewRoute = AppFamilyViewRouteImport.update({
  id: '/family/view',
  path: '/family/view',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyEditRoute = AppFamilyEditRouteImport.update({
  id: '/family/edit',
  path: '/family/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyAddRoute = AppFamilyAddRouteImport.update({
  id: '/family/add',
  path: '/family/add',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsAddRoute = AppAssetsAddRouteImport.update({
  id: '/assets/add',
  path: '/assets/add',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementCreateRoute = AppAgreementCreateRouteImport.update({
  id: '/agreement/create',
  path: '/agreement/create',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiFileKeyRoute = ApiFileKeyRouteImport.update({
  id: '/api/file/$key',
  path: '/api/file/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileSplatRoute = ApiFileSplatRouteImport.update({
  id: '/api/file/$',
  path: '/api/file/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamilySearchRoute = ApiFamilySearchRouteImport.update({
  id: '/api/family/search',
  path: '/api/family/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamilySplatRoute = ApiFamilySplatRouteImport.update({
  id: '/api/family/$',
  path: '/api/family/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetSplatRoute = ApiAssetSplatRouteImport.update({
  id: '/api/asset/$',
  path: '/api/asset/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgreementSplatRoute = ApiAgreementSplatRouteImport.update({
  id: '/api/agreement/$',
  path: '/api/agreement/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentChatRoute = ApiAgentChatRouteImport.update({
  id: '/api/agent/chat',
  path: '/api/agent/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssetsViewIndexRoute = AppAssetsViewIndexRouteImport.update({
  id: '/assets/view/',
  path: '/assets/view/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsEditIndexRoute = AppAssetsEditIndexRouteImport.update({
  id: '/assets/edit/',
  path: '/assets/edit/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementViewIndexRoute = AppAgreementViewIndexRouteImport.update({
  id: '/agreement/view/',
  path: '/agreement/view/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAssetsIndexRoute = AppAdminAssetsIndexRouteImport.update({
  id: '/admin/assets/',
  path: '/admin/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAgreementsIndexRoute = AppAdminAgreementsIndexRouteImport.update({
  id: '/admin/agreements/',
  path: '/admin/agreements/',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadJsonIndexRoute = ApiUploadJsonIndexRouteImport.update({
  id: '/api/upload/json/',
  path: '/api/upload/json/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssetsViewIdRoute = AppAssetsViewIdRouteImport.update({
  id: '/assets/view/$id',
  path: '/assets/view/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsEditIdRoute = AppAssetsEditIdRouteImport.update({
  id: '/assets/edit/$id',
  path: '/assets/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementViewIdRoute = AppAgreementViewIdRouteImport.update({
  id: '/agreement/view/$id',
  path: '/agreement/view/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersIdRoute = AppAdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiUserProfileSplatRoute = ApiUserProfileSplatRouteImport.update({
  id: '/api/user/profile/$',
  path: '/api/user/profile/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserNotificationPreferencesSplatRoute =
  ApiUserNotificationPreferencesSplatRouteImport.update({
    id: '/api/user/notification-preferences/$',
    path: '/api/user/notification-preferences/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentPendingActionsConfirmRoute =
  ApiAgentPendingActionsConfirmRouteImport.update({
    id: '/api/agent/pending-actions/confirm',
    path: '/api/agent/pending-actions/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentConversationsSplatRoute =
  ApiAgentConversationsSplatRouteImport.update({
    id: '/api/agent/conversations/$',
    path: '/api/agent/conversations/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/api/admin/users/$id',
  path: '/api/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersSplatRoute = ApiAdminUsersSplatRouteImport.update({
  id: '/api/admin/users/$',
  path: '/api/admin/users/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionSplatRoute = ApiAdminSessionSplatRouteImport.update({
  id: '/api/admin/session/$',
  path: '/api/admin/session/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutSplatRoute = ApiAdminLogoutSplatRouteImport.update({
  id: '/api/admin/logout/$',
  path: '/api/admin/logout/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginSplatRoute = ApiAdminLoginSplatRouteImport.update({
  id: '/api/admin/login/$',
  path: '/api/admin/login/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAssetsSplatRoute = ApiAdminAssetsSplatRouteImport.update({
  id: '/api/admin/assets/$',
  path: '/api/admin/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAgreementsSplatRoute = ApiAdminAgreementsSplatRouteImport.update({
  id: '/api/admin/agreements/$',
  path: '/api/admin/agreements/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminAgreementsSignByIcIndexRoute =
  AppAdminAgreementsSignByIcIndexRouteImport.update({
    id: '/admin/agreements/sign-by-ic/',
    path: '/admin/agreements/sign-by-ic/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAgreementsPendingWitnessIndexRoute =
  AppAdminAgreementsPendingWitnessIndexRouteImport.update({
    id: '/admin/agreements/pending-witness/',
    path: '/admin/agreements/pending-witness/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiAgreementIdStatusSplatRoute =
  ApiAgreementIdStatusSplatRouteImport.update({
    id: '/api/agreement/$id/status/$',
    path: '/api/agreement/$id/status/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgreementIdBeneficiariesSplatRoute =
  ApiAgreementIdBeneficiariesSplatRouteImport.update({
    id: '/api/agreement/$id/beneficiaries/$',
    path: '/api/agreement/$id/beneficiaries/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgreementIdAssetsSplatRoute =
  ApiAgreementIdAssetsSplatRouteImport.update({
    id: '/api/agreement/$id/assets/$',
    path: '/api/agreement/$id/assets/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentConversationsIdSplatRoute =
  ApiAgentConversationsIdSplatRouteImport.update({
    id: '/api/agent/conversations/$id/$',
    path: '/api/agent/conversations/$id/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAgreementsSignOnBehalfSplatRoute =
  ApiAdminAgreementsSignOnBehalfSplatRouteImport.update({
    id: '/api/admin/agreements/sign-on-behalf/$',
    path: '/api/admin/agreements/sign-on-behalf/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAgreementsPendingWitnessSplatRoute =
  ApiAdminAgreementsPendingWitnessSplatRouteImport.update({
    id: '/api/admin/agreements/pending-witness/$',
    path: '/api/admin/agreements/pending-witness/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAgreementsIdSplatRoute =
  ApiAdminAgreementsIdSplatRouteImport.update({
    id: '/api/admin/agreements/$id/$',
    path: '/api/admin/agreements/$id/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgreementIdSignWitnessSplatRoute =
  ApiAgreementIdSignWitnessSplatRouteImport.update({
    id: '/api/agreement/$id/sign/witness/$',
    path: '/api/agreement/$id/sign/witness/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgreementIdSignOwnerSplatRoute =
  ApiAgreementIdSignOwnerSplatRouteImport.update({
    id: '/api/agreement/$id/sign/owner/$',
    path: '/api/agreement/$id/sign/owner/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgreementIdSignBeneficiarySplatRoute =
  ApiAgreementIdSignBeneficiarySplatRouteImport.update({
    id: '/api/agreement/$id/sign/beneficiary/$',
    path: '/api/agreement/$id/sign/beneficiary/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAgreementsByIcIcNumberSplatRoute =
  ApiAdminAgreementsByIcIcNumberSplatRouteImport.update({
    id: '/api/admin/agreements/by-ic/$icNumber/$',
    path: '/api/admin/agreements/by-ic/$icNumber/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/test-upload': typeof TestUploadRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agreement/$': typeof ApiAgreementSplatRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/family/$': typeof ApiFamilySplatRoute
  '/api/family/search': typeof ApiFamilySearchRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/agreement/create': typeof AppAgreementCreateRoute
  '/app/assets/add': typeof AppAssetsAddRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/edit': typeof AppFamilyEditRoute
  '/app/family/view': typeof AppFamilyViewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/view': typeof AppProfileViewRoute
  '/api/upload': typeof ApiUploadIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/agreement': typeof AppAgreementIndexRoute
  '/app/assets': typeof AppAssetsIndexRoute
  '/app/family': typeof AppFamilyIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/api/admin/agreements/$': typeof ApiAdminAgreementsSplatRoute
  '/api/admin/assets/$': typeof ApiAdminAssetsSplatRoute
  '/api/admin/login/$': typeof ApiAdminLoginSplatRoute
  '/api/admin/logout/$': typeof ApiAdminLogoutSplatRoute
  '/api/admin/session/$': typeof ApiAdminSessionSplatRoute
  '/api/admin/users/$': typeof ApiAdminUsersSplatRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/agent/conversations/$': typeof ApiAgentConversationsSplatRoute
  '/api/agent/pending-actions/confirm': typeof ApiAgentPendingActionsConfirmRoute
  '/api/user/notification-preferences/$': typeof ApiUserNotificationPreferencesSplatRoute
  '/api/user/profile/$': typeof ApiUserProfileSplatRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/agreement/view/$id': typeof AppAgreementViewIdRoute
  '/app/assets/edit/$id': typeof AppAssetsEditIdRoute
  '/app/assets/view/$id': typeof AppAssetsViewIdRoute
  '/api/upload/json': typeof ApiUploadJsonIndexRoute
  '/app/admin/agreements': typeof AppAdminAgreementsIndexRoute
  '/app/admin/assets': typeof AppAdminAssetsIndexRoute
  '/app/admin/users': typeof AppAdminUsersIndexRoute
  '/app/agreement/view': typeof AppAgreementViewIndexRoute
  '/app/assets/edit': typeof AppAssetsEditIndexRoute
  '/app/assets/view': typeof AppAssetsViewIndexRoute
  '/api/admin/agreements/$id/$': typeof ApiAdminAgreementsIdSplatRoute
  '/api/admin/agreements/pending-witness/$': typeof ApiAdminAgreementsPendingWitnessSplatRoute
  '/api/admin/agreements/sign-on-behalf/$': typeof ApiAdminAgreementsSignOnBehalfSplatRoute
  '/api/agent/conversations/$id/$': typeof ApiAgentConversationsIdSplatRoute
  '/api/agreement/$id/assets/$': typeof ApiAgreementIdAssetsSplatRoute
  '/api/agreement/$id/beneficiaries/$': typeof ApiAgreementIdBeneficiariesSplatRoute
  '/api/agreement/$id/status/$': typeof ApiAgreementIdStatusSplatRoute
  '/app/admin/agreements/pending-witness': typeof AppAdminAgreementsPendingWitnessIndexRoute
  '/app/admin/agreements/sign-by-ic': typeof AppAdminAgreementsSignByIcIndexRoute
  '/api/admin/agreements/by-ic/$icNumber/$': typeof ApiAdminAgreementsByIcIcNumberSplatRoute
  '/api/agreement/$id/sign/beneficiary/$': typeof ApiAgreementIdSignBeneficiarySplatRoute
  '/api/agreement/$id/sign/owner/$': typeof ApiAgreementIdSignOwnerSplatRoute
  '/api/agreement/$id/sign/witness/$': typeof ApiAgreementIdSignWitnessSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/test-upload': typeof TestUploadRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agreement/$': typeof ApiAgreementSplatRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/family/$': typeof ApiFamilySplatRoute
  '/api/family/search': typeof ApiFamilySearchRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/agreement/create': typeof AppAgreementCreateRoute
  '/app/assets/add': typeof AppAssetsAddRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/edit': typeof AppFamilyEditRoute
  '/app/family/view': typeof AppFamilyViewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/view': typeof AppProfileViewRoute
  '/api/upload': typeof ApiUploadIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/agreement': typeof AppAgreementIndexRoute
  '/app/assets': typeof AppAssetsIndexRoute
  '/app/family': typeof AppFamilyIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/api/admin/agreements/$': typeof ApiAdminAgreementsSplatRoute
  '/api/admin/assets/$': typeof ApiAdminAssetsSplatRoute
  '/api/admin/login/$': typeof ApiAdminLoginSplatRoute
  '/api/admin/logout/$': typeof ApiAdminLogoutSplatRoute
  '/api/admin/session/$': typeof ApiAdminSessionSplatRoute
  '/api/admin/users/$': typeof ApiAdminUsersSplatRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/agent/conversations/$': typeof ApiAgentConversationsSplatRoute
  '/api/agent/pending-actions/confirm': typeof ApiAgentPendingActionsConfirmRoute
  '/api/user/notification-preferences/$': typeof ApiUserNotificationPreferencesSplatRoute
  '/api/user/profile/$': typeof ApiUserProfileSplatRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/agreement/view/$id': typeof AppAgreementViewIdRoute
  '/app/assets/edit/$id': typeof AppAssetsEditIdRoute
  '/app/assets/view/$id': typeof AppAssetsViewIdRoute
  '/api/upload/json': typeof ApiUploadJsonIndexRoute
  '/app/admin/agreements': typeof AppAdminAgreementsIndexRoute
  '/app/admin/assets': typeof AppAdminAssetsIndexRoute
  '/app/admin/users': typeof AppAdminUsersIndexRoute
  '/app/agreement/view': typeof AppAgreementViewIndexRoute
  '/app/assets/edit': typeof AppAssetsEditIndexRoute
  '/app/assets/view': typeof AppAssetsViewIndexRoute
  '/api/admin/agreements/$id/$': typeof ApiAdminAgreementsIdSplatRoute
  '/api/admin/agreements/pending-witness/$': typeof ApiAdminAgreementsPendingWitnessSplatRoute
  '/api/admin/agreements/sign-on-behalf/$': typeof ApiAdminAgreementsSignOnBehalfSplatRoute
  '/api/agent/conversations/$id/$': typeof ApiAgentConversationsIdSplatRoute
  '/api/agreement/$id/assets/$': typeof ApiAgreementIdAssetsSplatRoute
  '/api/agreement/$id/beneficiaries/$': typeof ApiAgreementIdBeneficiariesSplatRoute
  '/api/agreement/$id/status/$': typeof ApiAgreementIdStatusSplatRoute
  '/app/admin/agreements/pending-witness': typeof AppAdminAgreementsPendingWitnessIndexRoute
  '/app/admin/agreements/sign-by-ic': typeof AppAdminAgreementsSignByIcIndexRoute
  '/api/admin/agreements/by-ic/$icNumber/$': typeof ApiAdminAgreementsByIcIcNumberSplatRoute
  '/api/agreement/$id/sign/beneficiary/$': typeof ApiAgreementIdSignBeneficiarySplatRoute
  '/api/agreement/$id/sign/owner/$': typeof ApiAgreementIdSignOwnerSplatRoute
  '/api/agreement/$id/sign/witness/$': typeof ApiAgreementIdSignWitnessSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/test-upload': typeof TestUploadRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agreement/$': typeof ApiAgreementSplatRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/family/$': typeof ApiFamilySplatRoute
  '/api/family/search': typeof ApiFamilySearchRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/agreement/create': typeof AppAgreementCreateRoute
  '/app/assets/add': typeof AppAssetsAddRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/edit': typeof AppFamilyEditRoute
  '/app/family/view': typeof AppFamilyViewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/view': typeof AppProfileViewRoute
  '/api/upload/': typeof ApiUploadIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/agreement/': typeof AppAgreementIndexRoute
  '/app/assets/': typeof AppAssetsIndexRoute
  '/app/family/': typeof AppFamilyIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/api/admin/agreements/$': typeof ApiAdminAgreementsSplatRoute
  '/api/admin/assets/$': typeof ApiAdminAssetsSplatRoute
  '/api/admin/login/$': typeof ApiAdminLoginSplatRoute
  '/api/admin/logout/$': typeof ApiAdminLogoutSplatRoute
  '/api/admin/session/$': typeof ApiAdminSessionSplatRoute
  '/api/admin/users/$': typeof ApiAdminUsersSplatRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/agent/conversations/$': typeof ApiAgentConversationsSplatRoute
  '/api/agent/pending-actions/confirm': typeof ApiAgentPendingActionsConfirmRoute
  '/api/user/notification-preferences/$': typeof ApiUserNotificationPreferencesSplatRoute
  '/api/user/profile/$': typeof ApiUserProfileSplatRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/agreement/view/$id': typeof AppAgreementViewIdRoute
  '/app/assets/edit/$id': typeof AppAssetsEditIdRoute
  '/app/assets/view/$id': typeof AppAssetsViewIdRoute
  '/api/upload/json/': typeof ApiUploadJsonIndexRoute
  '/app/admin/agreements/': typeof AppAdminAgreementsIndexRoute
  '/app/admin/assets/': typeof AppAdminAssetsIndexRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
  '/app/agreement/view/': typeof AppAgreementViewIndexRoute
  '/app/assets/edit/': typeof AppAssetsEditIndexRoute
  '/app/assets/view/': typeof AppAssetsViewIndexRoute
  '/api/admin/agreements/$id/$': typeof ApiAdminAgreementsIdSplatRoute
  '/api/admin/agreements/pending-witness/$': typeof ApiAdminAgreementsPendingWitnessSplatRoute
  '/api/admin/agreements/sign-on-behalf/$': typeof ApiAdminAgreementsSignOnBehalfSplatRoute
  '/api/agent/conversations/$id/$': typeof ApiAgentConversationsIdSplatRoute
  '/api/agreement/$id/assets/$': typeof ApiAgreementIdAssetsSplatRoute
  '/api/agreement/$id/beneficiaries/$': typeof ApiAgreementIdBeneficiariesSplatRoute
  '/api/agreement/$id/status/$': typeof ApiAgreementIdStatusSplatRoute
  '/app/admin/agreements/pending-witness/': typeof AppAdminAgreementsPendingWitnessIndexRoute
  '/app/admin/agreements/sign-by-ic/': typeof AppAdminAgreementsSignByIcIndexRoute
  '/api/admin/agreements/by-ic/$icNumber/$': typeof ApiAdminAgreementsByIcIcNumberSplatRoute
  '/api/agreement/$id/sign/beneficiary/$': typeof ApiAgreementIdSignBeneficiarySplatRoute
  '/api/agreement/$id/sign/owner/$': typeof ApiAgreementIdSignOwnerSplatRoute
  '/api/agreement/$id/sign/witness/$': typeof ApiAgreementIdSignWitnessSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/test-upload'
    | '/admin/login'
    | '/app/dashboard'
    | '/api/agent/chat'
    | '/api/agreement/$'
    | '/api/asset/$'
    | '/api/auth/$'
    | '/api/family/$'
    | '/api/family/search'
    | '/api/file/$'
    | '/api/file/$key'
    | '/app/admin/dashboard'
    | '/app/agreement/create'
    | '/app/assets/add'
    | '/app/family/add'
    | '/app/family/edit'
    | '/app/family/view'
    | '/app/profile/edit'
    | '/app/profile/view'
    | '/api/upload'
    | '/app/admin'
    | '/app/agreement'
    | '/app/assets'
    | '/app/family'
    | '/app/profile'
    | '/app/settings'
    | '/api/admin/agreements/$'
    | '/api/admin/assets/$'
    | '/api/admin/login/$'
    | '/api/admin/logout/$'
    | '/api/admin/session/$'
    | '/api/admin/users/$'
    | '/api/admin/users/$id'
    | '/api/agent/conversations/$'
    | '/api/agent/pending-actions/confirm'
    | '/api/user/notification-preferences/$'
    | '/api/user/profile/$'
    | '/app/admin/users/$id'
    | '/app/agreement/view/$id'
    | '/app/assets/edit/$id'
    | '/app/assets/view/$id'
    | '/api/upload/json'
    | '/app/admin/agreements'
    | '/app/admin/assets'
    | '/app/admin/users'
    | '/app/agreement/view'
    | '/app/assets/edit'
    | '/app/assets/view'
    | '/api/admin/agreements/$id/$'
    | '/api/admin/agreements/pending-witness/$'
    | '/api/admin/agreements/sign-on-behalf/$'
    | '/api/agent/conversations/$id/$'
    | '/api/agreement/$id/assets/$'
    | '/api/agreement/$id/beneficiaries/$'
    | '/api/agreement/$id/status/$'
    | '/app/admin/agreements/pending-witness'
    | '/app/admin/agreements/sign-by-ic'
    | '/api/admin/agreements/by-ic/$icNumber/$'
    | '/api/agreement/$id/sign/beneficiary/$'
    | '/api/agreement/$id/sign/owner/$'
    | '/api/agreement/$id/sign/witness/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/test-upload'
    | '/admin/login'
    | '/app/dashboard'
    | '/api/agent/chat'
    | '/api/agreement/$'
    | '/api/asset/$'
    | '/api/auth/$'
    | '/api/family/$'
    | '/api/family/search'
    | '/api/file/$'
    | '/api/file/$key'
    | '/app/admin/dashboard'
    | '/app/agreement/create'
    | '/app/assets/add'
    | '/app/family/add'
    | '/app/family/edit'
    | '/app/family/view'
    | '/app/profile/edit'
    | '/app/profile/view'
    | '/api/upload'
    | '/app/admin'
    | '/app/agreement'
    | '/app/assets'
    | '/app/family'
    | '/app/profile'
    | '/app/settings'
    | '/api/admin/agreements/$'
    | '/api/admin/assets/$'
    | '/api/admin/login/$'
    | '/api/admin/logout/$'
    | '/api/admin/session/$'
    | '/api/admin/users/$'
    | '/api/admin/users/$id'
    | '/api/agent/conversations/$'
    | '/api/agent/pending-actions/confirm'
    | '/api/user/notification-preferences/$'
    | '/api/user/profile/$'
    | '/app/admin/users/$id'
    | '/app/agreement/view/$id'
    | '/app/assets/edit/$id'
    | '/app/assets/view/$id'
    | '/api/upload/json'
    | '/app/admin/agreements'
    | '/app/admin/assets'
    | '/app/admin/users'
    | '/app/agreement/view'
    | '/app/assets/edit'
    | '/app/assets/view'
    | '/api/admin/agreements/$id/$'
    | '/api/admin/agreements/pending-witness/$'
    | '/api/admin/agreements/sign-on-behalf/$'
    | '/api/agent/conversations/$id/$'
    | '/api/agreement/$id/assets/$'
    | '/api/agreement/$id/beneficiaries/$'
    | '/api/agreement/$id/status/$'
    | '/app/admin/agreements/pending-witness'
    | '/app/admin/agreements/sign-by-ic'
    | '/api/admin/agreements/by-ic/$icNumber/$'
    | '/api/agreement/$id/sign/beneficiary/$'
    | '/api/agreement/$id/sign/owner/$'
    | '/api/agreement/$id/sign/witness/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/test-upload'
    | '/admin/login'
    | '/app/dashboard'
    | '/api/agent/chat'
    | '/api/agreement/$'
    | '/api/asset/$'
    | '/api/auth/$'
    | '/api/family/$'
    | '/api/family/search'
    | '/api/file/$'
    | '/api/file/$key'
    | '/app/admin/dashboard'
    | '/app/agreement/create'
    | '/app/assets/add'
    | '/app/family/add'
    | '/app/family/edit'
    | '/app/family/view'
    | '/app/profile/edit'
    | '/app/profile/view'
    | '/api/upload/'
    | '/app/admin/'
    | '/app/agreement/'
    | '/app/assets/'
    | '/app/family/'
    | '/app/profile/'
    | '/app/settings/'
    | '/api/admin/agreements/$'
    | '/api/admin/assets/$'
    | '/api/admin/login/$'
    | '/api/admin/logout/$'
    | '/api/admin/session/$'
    | '/api/admin/users/$'
    | '/api/admin/users/$id'
    | '/api/agent/conversations/$'
    | '/api/agent/pending-actions/confirm'
    | '/api/user/notification-preferences/$'
    | '/api/user/profile/$'
    | '/app/admin/users/$id'
    | '/app/agreement/view/$id'
    | '/app/assets/edit/$id'
    | '/app/assets/view/$id'
    | '/api/upload/json/'
    | '/app/admin/agreements/'
    | '/app/admin/assets/'
    | '/app/admin/users/'
    | '/app/agreement/view/'
    | '/app/assets/edit/'
    | '/app/assets/view/'
    | '/api/admin/agreements/$id/$'
    | '/api/admin/agreements/pending-witness/$'
    | '/api/admin/agreements/sign-on-behalf/$'
    | '/api/agent/conversations/$id/$'
    | '/api/agreement/$id/assets/$'
    | '/api/agreement/$id/beneficiaries/$'
    | '/api/agreement/$id/status/$'
    | '/app/admin/agreements/pending-witness/'
    | '/app/admin/agreements/sign-by-ic/'
    | '/api/admin/agreements/by-ic/$icNumber/$'
    | '/api/agreement/$id/sign/beneficiary/$'
    | '/api/agreement/$id/sign/owner/$'
    | '/api/agreement/$id/sign/witness/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  TestUploadRoute: typeof TestUploadRoute
  ApiAgentChatRoute: typeof ApiAgentChatRoute
  ApiAgreementSplatRoute: typeof ApiAgreementSplatRoute
  ApiAssetSplatRoute: typeof ApiAssetSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFamilySplatRoute: typeof ApiFamilySplatRoute
  ApiFamilySearchRoute: typeof ApiFamilySearchRoute
  ApiFileSplatRoute: typeof ApiFileSplatRoute
  ApiFileKeyRoute: typeof ApiFileKeyRoute
  ApiUploadIndexRoute: typeof ApiUploadIndexRoute
  ApiAdminAgreementsSplatRoute: typeof ApiAdminAgreementsSplatRoute
  ApiAdminAssetsSplatRoute: typeof ApiAdminAssetsSplatRoute
  ApiAdminLoginSplatRoute: typeof ApiAdminLoginSplatRoute
  ApiAdminLogoutSplatRoute: typeof ApiAdminLogoutSplatRoute
  ApiAdminSessionSplatRoute: typeof ApiAdminSessionSplatRoute
  ApiAdminUsersSplatRoute: typeof ApiAdminUsersSplatRoute
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRoute
  ApiAgentConversationsSplatRoute: typeof ApiAgentConversationsSplatRoute
  ApiAgentPendingActionsConfirmRoute: typeof ApiAgentPendingActionsConfirmRoute
  ApiUserNotificationPreferencesSplatRoute: typeof ApiUserNotificationPreferencesSplatRoute
  ApiUserProfileSplatRoute: typeof ApiUserProfileSplatRoute
  ApiUploadJsonIndexRoute: typeof ApiUploadJsonIndexRoute
  ApiAdminAgreementsIdSplatRoute: typeof ApiAdminAgreementsIdSplatRoute
  ApiAdminAgreementsPendingWitnessSplatRoute: typeof ApiAdminAgreementsPendingWitnessSplatRoute
  ApiAdminAgreementsSignOnBehalfSplatRoute: typeof ApiAdminAgreementsSignOnBehalfSplatRoute
  ApiAgentConversationsIdSplatRoute: typeof ApiAgentConversationsIdSplatRoute
  ApiAgreementIdAssetsSplatRoute: typeof ApiAgreementIdAssetsSplatRoute
  ApiAgreementIdBeneficiariesSplatRoute: typeof ApiAgreementIdBeneficiariesSplatRoute
  ApiAgreementIdStatusSplatRoute: typeof ApiAgreementIdStatusSplatRoute
  ApiAdminAgreementsByIcIcNumberSplatRoute: typeof ApiAdminAgreementsByIcIcNumberSplatRoute
  ApiAgreementIdSignBeneficiarySplatRoute: typeof ApiAgreementIdSignBeneficiarySplatRoute
  ApiAgreementIdSignOwnerSplatRoute: typeof ApiAgreementIdSignOwnerSplatRoute
  ApiAgreementIdSignWitnessSplatRoute: typeof ApiAgreementIdSignWitnessSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-upload': {
      id: '/test-upload'
      path: '/test-upload'
      fullPath: '/test-upload'
      preLoaderRoute: typeof TestUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family/': {
      id: '/app/family/'
      path: '/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof AppFamilyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/': {
      id: '/app/assets/'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agreement/': {
      id: '/app/agreement/'
      path: '/agreement'
      fullPath: '/app/agreement'
      preLoaderRoute: typeof AppAgreementIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/upload/': {
      id: '/api/upload/'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/view': {
      id: '/app/profile/view'
      path: '/profile/view'
      fullPath: '/app/profile/view'
      preLoaderRoute: typeof AppProfileViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family/view': {
      id: '/app/family/view'
      path: '/family/view'
      fullPath: '/app/family/view'
      preLoaderRoute: typeof AppFamilyViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family/edit': {
      id: '/app/family/edit'
      path: '/family/edit'
      fullPath: '/app/family/edit'
      preLoaderRoute: typeof AppFamilyEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family/add': {
      id: '/app/family/add'
      path: '/family/add'
      fullPath: '/app/family/add'
      preLoaderRoute: typeof AppFamilyAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/add': {
      id: '/app/assets/add'
      path: '/assets/add'
      fullPath: '/app/assets/add'
      preLoaderRoute: typeof AppAssetsAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agreement/create': {
      id: '/app/agreement/create'
      path: '/agreement/create'
      fullPath: '/app/agreement/create'
      preLoaderRoute: typeof AppAgreementCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/file/$key': {
      id: '/api/file/$key'
      path: '/api/file/$key'
      fullPath: '/api/file/$key'
      preLoaderRoute: typeof ApiFileKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/$': {
      id: '/api/file/$'
      path: '/api/file/$'
      fullPath: '/api/file/$'
      preLoaderRoute: typeof ApiFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/family/search': {
      id: '/api/family/search'
      path: '/api/family/search'
      fullPath: '/api/family/search'
      preLoaderRoute: typeof ApiFamilySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/family/$': {
      id: '/api/family/$'
      path: '/api/family/$'
      fullPath: '/api/family/$'
      preLoaderRoute: typeof ApiFamilySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$': {
      id: '/api/asset/$'
      path: '/api/asset/$'
      fullPath: '/api/asset/$'
      preLoaderRoute: typeof ApiAssetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agreement/$': {
      id: '/api/agreement/$'
      path: '/api/agreement/$'
      fullPath: '/api/agreement/$'
      preLoaderRoute: typeof ApiAgreementSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/chat': {
      id: '/api/agent/chat'
      path: '/api/agent/chat'
      fullPath: '/api/agent/chat'
      preLoaderRoute: typeof ApiAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assets/view/': {
      id: '/app/assets/view/'
      path: '/assets/view'
      fullPath: '/app/assets/view'
      preLoaderRoute: typeof AppAssetsViewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/edit/': {
      id: '/app/assets/edit/'
      path: '/assets/edit'
      fullPath: '/app/assets/edit'
      preLoaderRoute: typeof AppAssetsEditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agreement/view/': {
      id: '/app/agreement/view/'
      path: '/agreement/view'
      fullPath: '/app/agreement/view'
      preLoaderRoute: typeof AppAgreementViewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users/': {
      id: '/app/admin/users/'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/assets/': {
      id: '/app/admin/assets/'
      path: '/admin/assets'
      fullPath: '/app/admin/assets'
      preLoaderRoute: typeof AppAdminAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/agreements/': {
      id: '/app/admin/agreements/'
      path: '/admin/agreements'
      fullPath: '/app/admin/agreements'
      preLoaderRoute: typeof AppAdminAgreementsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/upload/json/': {
      id: '/api/upload/json/'
      path: '/api/upload/json'
      fullPath: '/api/upload/json'
      preLoaderRoute: typeof ApiUploadJsonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assets/view/$id': {
      id: '/app/assets/view/$id'
      path: '/assets/view/$id'
      fullPath: '/app/assets/view/$id'
      preLoaderRoute: typeof AppAssetsViewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/edit/$id': {
      id: '/app/assets/edit/$id'
      path: '/assets/edit/$id'
      fullPath: '/app/assets/edit/$id'
      preLoaderRoute: typeof AppAssetsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agreement/view/$id': {
      id: '/app/agreement/view/$id'
      path: '/agreement/view/$id'
      fullPath: '/app/agreement/view/$id'
      preLoaderRoute: typeof AppAgreementViewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users/$id': {
      id: '/app/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/app/admin/users/$id'
      preLoaderRoute: typeof AppAdminUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/user/profile/$': {
      id: '/api/user/profile/$'
      path: '/api/user/profile/$'
      fullPath: '/api/user/profile/$'
      preLoaderRoute: typeof ApiUserProfileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/notification-preferences/$': {
      id: '/api/user/notification-preferences/$'
      path: '/api/user/notification-preferences/$'
      fullPath: '/api/user/notification-preferences/$'
      preLoaderRoute: typeof ApiUserNotificationPreferencesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/pending-actions/confirm': {
      id: '/api/agent/pending-actions/confirm'
      path: '/api/agent/pending-actions/confirm'
      fullPath: '/api/agent/pending-actions/confirm'
      preLoaderRoute: typeof ApiAgentPendingActionsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/conversations/$': {
      id: '/api/agent/conversations/$'
      path: '/api/agent/conversations/$'
      fullPath: '/api/agent/conversations/$'
      preLoaderRoute: typeof ApiAgentConversationsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/api/admin/users/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$': {
      id: '/api/admin/users/$'
      path: '/api/admin/users/$'
      fullPath: '/api/admin/users/$'
      preLoaderRoute: typeof ApiAdminUsersSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session/$': {
      id: '/api/admin/session/$'
      path: '/api/admin/session/$'
      fullPath: '/api/admin/session/$'
      preLoaderRoute: typeof ApiAdminSessionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout/$': {
      id: '/api/admin/logout/$'
      path: '/api/admin/logout/$'
      fullPath: '/api/admin/logout/$'
      preLoaderRoute: typeof ApiAdminLogoutSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login/$': {
      id: '/api/admin/login/$'
      path: '/api/admin/login/$'
      fullPath: '/api/admin/login/$'
      preLoaderRoute: typeof ApiAdminLoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/assets/$': {
      id: '/api/admin/assets/$'
      path: '/api/admin/assets/$'
      fullPath: '/api/admin/assets/$'
      preLoaderRoute: typeof ApiAdminAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/agreements/$': {
      id: '/api/admin/agreements/$'
      path: '/api/admin/agreements/$'
      fullPath: '/api/admin/agreements/$'
      preLoaderRoute: typeof ApiAdminAgreementsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/agreements/sign-by-ic/': {
      id: '/app/admin/agreements/sign-by-ic/'
      path: '/admin/agreements/sign-by-ic'
      fullPath: '/app/admin/agreements/sign-by-ic'
      preLoaderRoute: typeof AppAdminAgreementsSignByIcIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/agreements/pending-witness/': {
      id: '/app/admin/agreements/pending-witness/'
      path: '/admin/agreements/pending-witness'
      fullPath: '/app/admin/agreements/pending-witness'
      preLoaderRoute: typeof AppAdminAgreementsPendingWitnessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/agreement/$id/status/$': {
      id: '/api/agreement/$id/status/$'
      path: '/api/agreement/$id/status/$'
      fullPath: '/api/agreement/$id/status/$'
      preLoaderRoute: typeof ApiAgreementIdStatusSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agreement/$id/beneficiaries/$': {
      id: '/api/agreement/$id/beneficiaries/$'
      path: '/api/agreement/$id/beneficiaries/$'
      fullPath: '/api/agreement/$id/beneficiaries/$'
      preLoaderRoute: typeof ApiAgreementIdBeneficiariesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agreement/$id/assets/$': {
      id: '/api/agreement/$id/assets/$'
      path: '/api/agreement/$id/assets/$'
      fullPath: '/api/agreement/$id/assets/$'
      preLoaderRoute: typeof ApiAgreementIdAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/conversations/$id/$': {
      id: '/api/agent/conversations/$id/$'
      path: '/api/agent/conversations/$id/$'
      fullPath: '/api/agent/conversations/$id/$'
      preLoaderRoute: typeof ApiAgentConversationsIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/agreements/sign-on-behalf/$': {
      id: '/api/admin/agreements/sign-on-behalf/$'
      path: '/api/admin/agreements/sign-on-behalf/$'
      fullPath: '/api/admin/agreements/sign-on-behalf/$'
      preLoaderRoute: typeof ApiAdminAgreementsSignOnBehalfSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/agreements/pending-witness/$': {
      id: '/api/admin/agreements/pending-witness/$'
      path: '/api/admin/agreements/pending-witness/$'
      fullPath: '/api/admin/agreements/pending-witness/$'
      preLoaderRoute: typeof ApiAdminAgreementsPendingWitnessSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/agreements/$id/$': {
      id: '/api/admin/agreements/$id/$'
      path: '/api/admin/agreements/$id/$'
      fullPath: '/api/admin/agreements/$id/$'
      preLoaderRoute: typeof ApiAdminAgreementsIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agreement/$id/sign/witness/$': {
      id: '/api/agreement/$id/sign/witness/$'
      path: '/api/agreement/$id/sign/witness/$'
      fullPath: '/api/agreement/$id/sign/witness/$'
      preLoaderRoute: typeof ApiAgreementIdSignWitnessSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agreement/$id/sign/owner/$': {
      id: '/api/agreement/$id/sign/owner/$'
      path: '/api/agreement/$id/sign/owner/$'
      fullPath: '/api/agreement/$id/sign/owner/$'
      preLoaderRoute: typeof ApiAgreementIdSignOwnerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agreement/$id/sign/beneficiary/$': {
      id: '/api/agreement/$id/sign/beneficiary/$'
      path: '/api/agreement/$id/sign/beneficiary/$'
      fullPath: '/api/agreement/$id/sign/beneficiary/$'
      preLoaderRoute: typeof ApiAgreementIdSignBeneficiarySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/agreements/by-ic/$icNumber/$': {
      id: '/api/admin/agreements/by-ic/$icNumber/$'
      path: '/api/admin/agreements/by-ic/$icNumber/$'
      fullPath: '/api/admin/agreements/by-ic/$icNumber/$'
      preLoaderRoute: typeof ApiAdminAgreementsByIcIcNumberSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAgreementCreateRoute: typeof AppAgreementCreateRoute
  AppAssetsAddRoute: typeof AppAssetsAddRoute
  AppFamilyAddRoute: typeof AppFamilyAddRoute
  AppFamilyEditRoute: typeof AppFamilyEditRoute
  AppFamilyViewRoute: typeof AppFamilyViewRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileViewRoute: typeof AppProfileViewRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAgreementIndexRoute: typeof AppAgreementIndexRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppFamilyIndexRoute: typeof AppFamilyIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppAdminUsersIdRoute: typeof AppAdminUsersIdRoute
  AppAgreementViewIdRoute: typeof AppAgreementViewIdRoute
  AppAssetsEditIdRoute: typeof AppAssetsEditIdRoute
  AppAssetsViewIdRoute: typeof AppAssetsViewIdRoute
  AppAdminAgreementsIndexRoute: typeof AppAdminAgreementsIndexRoute
  AppAdminAssetsIndexRoute: typeof AppAdminAssetsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppAgreementViewIndexRoute: typeof AppAgreementViewIndexRoute
  AppAssetsEditIndexRoute: typeof AppAssetsEditIndexRoute
  AppAssetsViewIndexRoute: typeof AppAssetsViewIndexRoute
  AppAdminAgreementsPendingWitnessIndexRoute: typeof AppAdminAgreementsPendingWitnessIndexRoute
  AppAdminAgreementsSignByIcIndexRoute: typeof AppAdminAgreementsSignByIcIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAgreementCreateRoute: AppAgreementCreateRoute,
  AppAssetsAddRoute: AppAssetsAddRoute,
  AppFamilyAddRoute: AppFamilyAddRoute,
  AppFamilyEditRoute: AppFamilyEditRoute,
  AppFamilyViewRoute: AppFamilyViewRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileViewRoute: AppProfileViewRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAgreementIndexRoute: AppAgreementIndexRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppFamilyIndexRoute: AppFamilyIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppAdminUsersIdRoute: AppAdminUsersIdRoute,
  AppAgreementViewIdRoute: AppAgreementViewIdRoute,
  AppAssetsEditIdRoute: AppAssetsEditIdRoute,
  AppAssetsViewIdRoute: AppAssetsViewIdRoute,
  AppAdminAgreementsIndexRoute: AppAdminAgreementsIndexRoute,
  AppAdminAssetsIndexRoute: AppAdminAssetsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppAgreementViewIndexRoute: AppAgreementViewIndexRoute,
  AppAssetsEditIndexRoute: AppAssetsEditIndexRoute,
  AppAssetsViewIndexRoute: AppAssetsViewIndexRoute,
  AppAdminAgreementsPendingWitnessIndexRoute:
    AppAdminAgreementsPendingWitnessIndexRoute,
  AppAdminAgreementsSignByIcIndexRoute: AppAdminAgreementsSignByIcIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  TestUploadRoute: TestUploadRoute,
  ApiAgentChatRoute: ApiAgentChatRoute,
  ApiAgreementSplatRoute: ApiAgreementSplatRoute,
  ApiAssetSplatRoute: ApiAssetSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFamilySplatRoute: ApiFamilySplatRoute,
  ApiFamilySearchRoute: ApiFamilySearchRoute,
  ApiFileSplatRoute: ApiFileSplatRoute,
  ApiFileKeyRoute: ApiFileKeyRoute,
  ApiUploadIndexRoute: ApiUploadIndexRoute,
  ApiAdminAgreementsSplatRoute: ApiAdminAgreementsSplatRoute,
  ApiAdminAssetsSplatRoute: ApiAdminAssetsSplatRoute,
  ApiAdminLoginSplatRoute: ApiAdminLoginSplatRoute,
  ApiAdminLogoutSplatRoute: ApiAdminLogoutSplatRoute,
  ApiAdminSessionSplatRoute: ApiAdminSessionSplatRoute,
  ApiAdminUsersSplatRoute: ApiAdminUsersSplatRoute,
  ApiAdminUsersIdRoute: ApiAdminUsersIdRoute,
  ApiAgentConversationsSplatRoute: ApiAgentConversationsSplatRoute,
  ApiAgentPendingActionsConfirmRoute: ApiAgentPendingActionsConfirmRoute,
  ApiUserNotificationPreferencesSplatRoute:
    ApiUserNotificationPreferencesSplatRoute,
  ApiUserProfileSplatRoute: ApiUserProfileSplatRoute,
  ApiUploadJsonIndexRoute: ApiUploadJsonIndexRoute,
  ApiAdminAgreementsIdSplatRoute: ApiAdminAgreementsIdSplatRoute,
  ApiAdminAgreementsPendingWitnessSplatRoute:
    ApiAdminAgreementsPendingWitnessSplatRoute,
  ApiAdminAgreementsSignOnBehalfSplatRoute:
    ApiAdminAgreementsSignOnBehalfSplatRoute,
  ApiAgentConversationsIdSplatRoute: ApiAgentConversationsIdSplatRoute,
  ApiAgreementIdAssetsSplatRoute: ApiAgreementIdAssetsSplatRoute,
  ApiAgreementIdBeneficiariesSplatRoute: ApiAgreementIdBeneficiariesSplatRoute,
  ApiAgreementIdStatusSplatRoute: ApiAgreementIdStatusSplatRoute,
  ApiAdminAgreementsByIcIcNumberSplatRoute:
    ApiAdminAgreementsByIcIcNumberSplatRoute,
  ApiAgreementIdSignBeneficiarySplatRoute:
    ApiAgreementIdSignBeneficiarySplatRoute,
  ApiAgreementIdSignOwnerSplatRoute: ApiAgreementIdSignOwnerSplatRoute,
  ApiAgreementIdSignWitnessSplatRoute: ApiAgreementIdSignWitnessSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
